### ISSUE TITLE
Legend saving/loading

### ISSUE THREAD

**Issue by crysb** [move-ucsb/DynamoVis#2]
After I 'save' a Legend layout and 'load' it again, it adds a blur to the map in that general area of the Legend that doesn't go away even after hitting 'reset'. However, it does seem to resolve itself once I change the map extent again.

<img width="1200" alt="legendLoad_blur2" src="https://user-images.githubusercontent.com/3245803/114780217-15dc5e80-9d45-11eb-9ff8-3fd46bc1a057.png">

**Comment by merttoka** [comment]
I cannot seem to reproduce this issue. Do you encounter this problem every time you 'load' a legend layout? Can you try with different base maps?

**Comment by crysb** [comment]
Thanks Mert, it doesn't seem to be every time and it was minor to begin with. I wasn't able to recreate the issue after testing it a few more times, so not sure what happened before. The legend saving and loading seems to be working properly for me.
