### ISSUE TITLE
Max opacity for "Underlay" feature is still translucent

### ISSUE THREAD

**Issue by crysb** [move-ucsb/DynamoVis#4]
Looks like even when **Underlay** is set at 100 for opacity, the underlay line shows up partially translucent. I tried changing it to a different color underlay and it still has the same issue.

<img width="800" alt="Screen Shot 2021-04-23 at 3 44 53 PM" src="https://user-images.githubusercontent.com/3245803/115936936-9c3f2180-a464-11eb-82e0-460472cae5c1.png">

**Comment by merttoka** [comment]
It looks like the maximum value of the opacity is not 100 but 255 (8-bit alpha channel). I see why it is confusing, I will make it work on the 1-100 range.

**Edit:** Addressed with commit https://github.com/move-ucsb/DynamoVis/commit/befa4f9471cff7025139772686feaf64f334531c
