### ISSUE TITLE
Input file issue

### ISSUE THREAD

**Issue by EmiTodorov** [move-ucsb/DynamoVis#8]
Hi there.
I got this message while trying to input file. I suppose the issue is somewhere in the input file. I tried to respect the rules for all 4 obligatory fields.  

-----New File-----
C:\Users\Emil\Downloads\DynamoVis-1.0\data\Victoria.csv

Using ID as individual-local-identifier
Using Long1(E) as location-long
Using Lat1(N) as location-lat
Using Timestamp as study-local-timestamp
Something bad happened: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

Many thanks for the help.
Emil

**Comment by merttoka** [comment]
Would you mind sharing a snippet from your data (3-5 lines and the headers)?

**Comment by EmiTodorov** [comment]
Here it is the screenshot of the data I am trying to upload. 
Many thanks for your kind assistance,
Emil 
![Untitled](https://user-images.githubusercontent.com/97021396/148173491-8a732e0f-13ca-4983-a934-7fe493d6f31b.jpg)

**Comment by merttoka** [comment]
Ah, I see. It looks like the `unique identifier` field is a row number for each row. DynamoVis expects this field as a unique ID/tag for each animal (or more broadly, each entity). 

If your data consists of the tracking points of only one entity, you can simply create another column (say `animal_id`) and assign the same ID for each row (for example `1` or `Leo`). If you have multiple entities, assign a different tag for different entities. Each entity ID/tag in your data will correspond to a different track in the visualization.

**Comment by EmiTodorov** [comment]
Many thanks! Now it works perfect!
Congratulations for your work done by developing this useful software. 
Best regards.
